---
ID: "ab7c7698-1ba0-4fbf-85c8-309492ea4b30"
Parent: "68e286d7-0468-44b6-bae5-11c6e59a2a2e"
Template: "fe5dd826-48c6-436d-b87a-7c4210c7413b"
Path: /sitecore/media library/Project/Verticals/Broward/Home page/Carousels/Default
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "6a8c25d5-421e-4eff-8ca9-f992444b2a5b"
