---
ID: "0fed636b-d833-4a8d-b7a2-1260d141cb20"
Parent: "cf924c98-8022-411f-aa6f-bd982856d53e"
Template: "4d50cdae-c2d9-4de8-b080-8f992bfb1b55"
Path: /sitecore/content/Verticals/Broward/Presentation/Headless Variants/Article List/Default
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "1965616b-6d46-4585-b16f-b7f7c3f0332f"
- Language: "fr-CA"
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "00e55f72-47d8-46d2-bcdf-5e0b6a4cc7fa"
